### ISSUE TITLE
実行中にサーバー切断するとクラッシュする

### ISSUE THREAD

**Issue by HiroRittsu** [tohsato-lab/process-manager#63]
condaコンテナが落ちる問題あり。
それと同時に、syncingが終わらない

**Comment by HiroRittsu** [comment]
syncingが終わらない問題は、ホスト鍵が変更されていることが原因だった。対応は別のissueで。

**Comment by HiroRittsu** [comment]
ゴミ箱削除した後クラッシュ
```
2022/03/25 13:08:00 {e85468245fd00cdbc23d39c8203edd1c main.py pytorch running {16254 true}}
2022/03/25 13:08:00 kill process
2022/03/25 13:08:00 exit status 2
2022/03/25 13:10:06 Connection already closed
2022/03/25 13:10:10 delete
2022/03/25 13:10:10 rm -rf ../../data/fa32cf1c3d6eb35df9a537dcf79d9ad9/
2022/03/25 13:10:11 delete
2022/03/25 13:10:11 rm -rf ../../data/e85468245fd00cdbc23d39c8203edd1c/
exit status 1
2022/03/25 13:10:13 exec done
panic: send on closed channel

goroutine 87 [running]:
conda/modules.(*Client).ReadPump.func1()
	/go/src/modules/client.go:75 +0x428
created by conda/modules.(*Client).ReadPump
	/go/src/modules/client.go:57 +0x877
```
